// Curated knowledge base for IP-SAKTI Sahayak — Comprehensive corpus
export interface KnowledgeEntry {
  title: string;
  category: string;
  jurisdiction: string;
  ipType: string;
  content: string;
  citation: string;
  sourceUrl?: string;
  version?: string;
  effectiveDate?: string;
  tags: string;
  authorityLevel?: string; // primary, secondary, tertiary
  enactingBody?: string;
}

export const knowledgeSeed: KnowledgeEntry[] = [
  // ===== INDIA - PATENTS =====
  {
    title: "Section 3(p) - Non-patentable inventions: Traditional Knowledge",
    category: "statute",
    jurisdiction: "india",
    ipType: "patent",
    content: `Under the Indian Patents Act, 1970 (as amended), Section 3(p) expressly bars patenting of "an invention which, in effect, is traditional knowledge or which is an aggregation or duplication of known properties of traditionally known component or components." This is one of the most critical provisions for Ayurveda. A classical Ayurvedic formulation described in authoritative texts (such as those listed in the First Schedule of the Drugs & Cosmetics Act) is considered traditional knowledge and is NOT patentable under Indian law. However, genuinely novel modifications, new delivery systems, or novel combinations that demonstrate inventive step beyond the traditional knowledge may still be patentable. The burden is on the applicant to show that the invention is not merely traditional knowledge. The Indian Patent Office routinely consults the Traditional Knowledge Digital Library (TKDL) to check prior art based on traditional knowledge.`,
    citation: "Patents Act, 1970, Section 3(p)",
    sourceUrl: "https://ipindia.gov.in/writereaddata/Portal/ev/sections/ps3.html",
    version: "As amended by Patents (Amendment) Act, 2005",
    effectiveDate: "2005-01-01",
    tags: "patent,traditional_knowledge,section_3p,non_patentable,ayurveda,tkdl",
  },
  {
    title: "Section 3(d) - Mere discovery of new form not patentable",
    category: "statute",
    jurisdiction: "india",
    ipType: "patent",
    content: `Section 3(d) of the Patents Act bars patenting of "the mere discovery of a new form of a known substance which does not result in the enhancement of the known efficacy of that substance." For Ayurvedic innovations, this means that merely converting a traditional kashayam (decoction) into a tablet form without enhanced therapeutic efficacy would not be patentable. However, if a new formulation form demonstrably improves bioavailability, stability, or therapeutic efficacy, it may overcome this bar. The Supreme Court in the landmark Novartis case (2013) interpreted this provision strictly, requiring enhanced therapeutic efficacy for pharmaceutical products. The Explanation to Section 3(d) clarifies that salts, esters, ethers, polymorphs, metabolites, pure form, particle size, isomers, mixtures, and complexes are considered the same substance unless they differ significantly in properties with regard to efficacy.`,
    citation: "Patents Act, 1970, Section 3(d); Novartis AG v. Union of India (2013) 6 SCC 1",
    sourceUrl: "https://ipindia.gov.in/writereaddata/Portal/ev/sections/ps3.html",
    version: "As amended 2005",
    effectiveDate: "2005-01-01",
    tags: "patent,new_form,efficacy,section_3d,ayurveda,novartis",
  },
  {
    title: "Section 3(e) - Mere admixture not resulting in synergistic properties",
    category: "statute",
    jurisdiction: "india",
    ipType: "patent",
    content: `Section 3(e) of the Patents Act states that "a substance obtained by a mere admixture resulting only in the aggregation of the properties of the components thereof or a process for producing such substance" is not an invention. For Ayurvedic formulations, if you combine two known herbs and the combination merely aggregates their individual properties without any synergistic or enhanced effect, it is not patentable. However, if you can demonstrate that the combination produces a synergistic effect — i.e., the combined effect is greater than the sum of individual effects — it may qualify as a patentable invention. This is particularly relevant for poly-herbal formulations common in Ayurveda. Scientific evidence showing synergy (e.g., bioavailability studies, pharmacological data) strengthens the patent application.`,
    citation: "Patents Act, 1970, Section 3(e)",
    sourceUrl: "https://ipindia.gov.in/writereaddata/Portal/ev/sections/ps3.html",
    version: "As amended 2005",
    effectiveDate: "2005-01-01",
    tags: "patent,admixture,synergy,section_3e,poly_herbal,ayurveda",
  },
  {
    title: "Section 10 - Contents of Patent Application and Disclosure Requirements",
    category: "statute",
    jurisdiction: "india",
    ipType: "patent",
    content: `Section 10 of the Patents Act mandates full and particular description of the invention. For Ayurvedic inventions: (1) The specification must disclose the source and geographical origin of biological material used; (2) If the invention uses traditional knowledge, the applicant must disclose how the invention goes beyond such TK; (3) For biological material depositable, the applicant must deposit with an authorized depository and include deposit details in the specification; (4) Best method of performing the invention must be described; (5) Claims must be clear, succinct, and fairly based on the matter disclosed in the specification. For AYUSH-related patents, the Patent Office may require additional evidence of efficacy beyond traditional usage, particularly for new therapeutic claims. The 2024 Rules have updated Form 1 to specifically require declaration of traditional knowledge and biological material origin.`,
    citation: "Patents Act, 1970, Section 10(4)(d)(ii); Patents Rules 2024, Rule 13",
    sourceUrl: "https://ipindia.gov.in",
    version: "As amended; 2024 Rules",
    effectiveDate: "2024-03-15",
    tags: "patent,disclosure,biological_material,specification,traditional_knowledge,form1",
  },
  {
    title: "Patent Rules 2024 - Updated procedures for AYUSH sector",
    category: "rule",
    jurisdiction: "india",
    ipType: "patent",
    content: `The Patents (Amendment) Rules, 2024 introduce several key changes relevant to Ayurvedic innovators: (1) Simplified fee structures with reduced fees for startups and small entities — startups pay only 20% of the standard fee; (2) Updated Form 1 requiring disclosure of biological material origin and traditional knowledge source; (3) Expedited examination available for AYUSH sector startups under Rule 24C; (4) Enhanced requirements for disclosure of traditional knowledge-based inventions; (5) Digital filing enhancements through the Indian Patent Office portal at ipindiaonline.gov.in; (6) Pre-grant opposition process (Section 25(1)) allows anyone to oppose a patent application before grant — useful for TKDL-based oppositions; (7) Post-grant opposition (Section 25(2)) within 12 months of publication of grant; (8) Time limit for examination response reduced, requiring faster prosecution; (9) New provisions for virtual hearings.`,
    citation: "Patents (Amendment) Rules, 2024, Rules 9, 13, 24C; Patents Act Sections 25(1), 25(2)",
    sourceUrl: "https://ipindia.gov.in",
    version: "2024",
    effectiveDate: "2024-03-15",
    tags: "patent,rules,2024,startup,ayush,filing,disclosure,opposition,expedited",
  },
  {
    title: "TKDL - Traditional Knowledge Digital Library",
    category: "guidance",
    jurisdiction: "india",
    ipType: "patent",
    content: `The Traditional Knowledge Digital Library (TKDL) is an Indian digital knowledge repository of traditional knowledge, especially relating to Ayurveda, Unani, Siddha and Yoga. Established in 2001, managed by CSIR and the Ministry of AYUSH. KEY FACTS: (1) Contains over 4.5 lakh formulations/practices from authoritative Ayurvedic texts including Charaka Samhita, Sushruta Samhita, Ashtanga Hridaya, Sharangdhara Samhita, Bhava Prakasha, Rasatarangini; (2) Formatted in patent-compatible International Patent Classification (IPC) codes; (3) Available in English, Japanese, French, German, and Spanish; (4) Access agreements with 13+ patent offices globally including Indian Patent Office, EPO, USPTO, JPO, UKIPO, CIPO (Canada), IP Australia; (5) Successfully challenged/prevented 250+ wrongful patents worldwide; (6) Key bio-piracy cases prevented: turmeric patent (USPTO), neem patent (EPO), ashwagandha patent. USAGE: Before filing any Ayurvedic patent, conduct TKDL prior art search. If your formulation is in TKDL, it CANNOT be patented. Focus patent claims on genuinely novel modifications beyond the documented TK. TKDL can be used defensively to challenge wrongful patents filed by others.`,
    citation: "TKDL Database, CSIR-Ministry of AYUSH; tkdl.res.in; TKDL Access Agreements",
    sourceUrl: "https://tkdl.res.in",
    version: "Current",
    effectiveDate: "2001-01-01",
    tags: "tkdl,traditional_knowledge,prior_art,patent,defensive,ayurveda,formulation,biopiracy",
  },
  {
    title: "Landmark Case: Turmeric Patent Revocation (USPTO)",
    category: "case_law",
    jurisdiction: "india",
    ipType: "patent",
    content: `In 1995, the University of Mississippi Medical Center was granted US Patent 5,401,504 for "Use of Turmeric in Wound Healing." CSIR (India) challenged this patent before the USPTO, arguing that turmeric's wound-healing properties were well-known traditional knowledge in India for centuries. CSIR presented evidence from ancient Sanskrit texts and published papers. In 1997, the USPTO revoked the patent — the first time a patent based on traditional knowledge was successfully challenged. This landmark case led to the creation of the TKDL. SIGNIFICANCE FOR AYURVEDA: (1) Demonstrated that traditional Ayurvedic knowledge qualifies as prior art; (2) Showed the need for systematic documentation of TK in patent-office-accessible formats; (3) Led directly to the establishment of TKDL; (4) Established precedent for challenging TK-based patents globally.`,
    citation: "US Patent 5,401,504 (revoked); CSIR v. University of Mississippi Medical Center, USPTO 1997",
    sourceUrl: "https://tkdl.res.in",
    version: "1997",
    effectiveDate: "1997-01-01",
    tags: "case_law,turmeric,patent,revocation,biopiracy,tkdl,prior_art,traditional_knowledge",
  },
  {
    title: "Landmark Case: Neem Patent Revocation (EPO)",
    category: "case_law",
    jurisdiction: "india",
    ipType: "patent",
    content: `The European Patent EP 0436257 B1, granted to W.R. Grace Company and USDA, claimed a method for controlling fungi on plants using neem seed oil extract. In 2005, the EPO Technical Board of Appeal revoked this patent following opposition by the Government of India (through CSIR), International Federation of Organic Agriculture Movements (IFOAM), and other parties. The Board found that the fungicidal effect of neem was part of traditional Indian knowledge and thus lacked novelty. This case took 10 years of litigation. SIGNIFICANCE: (1) Confirmed that traditional knowledge from developing countries constitutes valid prior art under European patent law; (2) Highlighted the cost and difficulty of challenging wrongful patents without systematic TK documentation; (3) Strengthened the case for TKDL and TK databases globally; (4) Prompted EU and international discussions on disclosure of TK origin in patent applications.`,
    citation: "EP 0436257 B1 (revoked); EPO Technical Board of Appeal, Case T 0416/01, 2005",
    sourceUrl: "https://www.epo.org",
    version: "2005",
    effectiveDate: "2005-03-08",
    tags: "case_law,neem,patent,revocation,epo,biopiracy,traditional_knowledge,prior_art",
  },
  {
    title: "Compulsory Licensing and Ayurvedic Patents",
    category: "statute",
    jurisdiction: "india",
    ipType: "patent",
    content: `Sections 84-92 of the Patents Act deal with compulsory licensing. Under Section 84, any person may apply for compulsory license after three years from grant if: (1) reasonable requirements of the public have not been satisfied; (2) the patented invention is not available at a reasonably affordable price; (3) the patented invention is not worked in the territory of India. Section 92 provides for compulsory licensing in circumstances of national emergency, extreme urgency, or public non-commercial use. For Ayurvedic innovations, this means: (a) If a patented Ayurvedic drug is not made available or is priced too high, compulsory licenses can be sought; (b) The Controller must consider whether the patentee has taken adequate steps to work the patent in India; (c) Landmark case: Natco v. Bayer (2012) — first compulsory license granted in India for a pharmaceutical (sorafenib). While this case involved a modern drug, the principles apply to patented Ayurvedic innovations as well.`,
    citation: "Patents Act, 1970, Sections 84-92; Natco Pharma v. Bayer, Compulsory License Application No. 1/2011",
    sourceUrl: "https://ipindia.gov.in",
    version: "As amended",
    effectiveDate: "1970-04-20",
    tags: "patent,compulsory_license,public_health,affordable,working,section84",
  },
  // ===== INDIA - GEOGRAPHICAL INDICATIONS =====
  {
    title: "Geographical Indications of Goods (Registration and Protection) Act, 1999",
    category: "statute",
    jurisdiction: "india",
    ipType: "gi",
    content: `The GI Act, 1999 protects GIs in India. For Ayurveda, GIs are highly relevant: (1) Region-specific medicinal plants and preparations can be protected; (2) REGISTERED AYURVEDIC GIs include: Mysore Agarbathi, Kerala Ayurvedic treatments (in various forms), Darjeeling Tea (relevant for herbal teas), Kangra Tea, Assam Orthodox Tea. POTENTIAL AYURVEDIC GIs: Specific varieties like Manipuri Black Rice, Banaras silk (packaging), region-specific Ayurvedic preparation methods. (3) REGISTRATION PROCESS: Application under Section 11 to GI Registry in Chennai → Examination → Advertisement in GI Journal → Opposition period (3 months) → Registration. (4) DURATION: 10 years, renewable indefinitely. (5) ADVANTAGES: Prevents misuse of region-specific names, adds market value (premium pricing), preserves traditional practices, provides collective protection for communities, can be held by producer associations/authorities. (6) GI HOLDER vs AUTHORIZED USER: The GI is registered in the name of an association/authority (Part A), while individual producers register as authorized users (Part B). (7) Section 22: GI infringement action.`,
    citation: "GI Act, 1999, Sections 1-11, 17, 22; GI Rules, 2002",
    sourceUrl: "https://ipindia.gov.in/gi.htm",
    version: "1999",
    effectiveDate: "2003-09-15",
    tags: "gi,geographical_indication,registration,region,medicinal_plants,ayurveda,kerala,mysore",
  },
  {
    title: "GI for Medicinal Plants and Ayurvedic Products - Practical Guide",
    category: "guidance",
    jurisdiction: "india",
    ipType: "gi",
    content: `PRACTICAL GUIDE FOR SEEKING GI PROTECTION FOR AYURVEDIC PRODUCTS: (1) ELIGIBILITY: Your product must have qualities, reputation, or characteristics attributable to its geographical origin. Examples: specific soil conditions affecting herb potency, traditional processing methods unique to a region, local climate contributing to unique qualities. (2) WHO CAN APPLY: Association of persons, producers, organization, or authority representing the interest of producers. Individual producers cannot apply for GI registration but can become authorized users. (3) DOCUMENTATION NEEDED: Proof of origin, historical evidence, uniqueness studies, quality parameters, map of geographical area, list of producers. (4) COSTS: Government fee is relatively modest (Rs. 5,000 for GI application). Professional costs vary. (5) EXAMPLES OF POTENTIAL AYURVEDIC GIs: Rajasthan Ashwagandha (higher withanolide content from specific soil), Kerala Panchakarma treatments, Himalayan Shilajit, Manipur medicinal rice varieties, specific regional Chyawanprash preparations. (6) GI vs TRADEMARK: GI is a collective right; trademark is an individual right. Both can coexist.`,
    citation: "GI Act, 1999; GI Rules, 2002; GI Registry, Chennai",
    sourceUrl: "https://ipindia.gov.in/gi.htm",
    version: "Current",
    effectiveDate: "2003-09-15",
    tags: "gi,practical_guide,medicinal_plants,ayurveda,application,ashwagandha,panchakarma",
  },
  // ===== INDIA - TRADEMARKS =====
  {
    title: "Trade Marks Act, 1999 - Protection for Ayurvedic brands",
    category: "statute",
    jurisdiction: "india",
    ipType: "trademark",
    content: `The Trade Marks Act, 1999 allows registration and protection of distinctive marks for Ayurvedic products. KEY PROVISIONS: (1) Section 2(zb): 'Trade mark' includes device, brand, heading, label, ticket, name, signature, word, letter, numeral, shape of goods, packaging, combination of colours; (2) Section 9 BARS: Marks that are descriptive, generic, or customary cannot be registered. 'Chyawanprash', 'Triphala', 'Ashwagandha' are GENERIC terms and cannot be trademarked alone; (3) Section 11: Relative grounds — marks confusingly similar to existing marks are refused; (4) Section 29: Infringement provisions; (5) Section 30: Permitted use (bona fide descriptive use); (6) NICE CLASSIFICATION for Ayurveda: Class 3 (cosmetics, soaps, essential oils), Class 5 (pharmaceuticals, dietetic substances, medical preparations), Class 29 (food products), Class 30 (spices, herbal teas), Class 44 (medical/health services); (7) FILING: Through IP India portal (ipindiaonline.gov.in) → Examination → Publication → Opposition (4 months) → Registration; (8) DURATION: 10 years, renewable indefinitely; (9) WELL-KNOWN MARKS: Some Ayurvedic brands may qualify for well-known mark status under Section 11(6)-(10). Examples: Dabur, Patanjali, Himalaya as brand names (not formulation names).`,
    citation: "Trade Marks Act, 1999, Sections 2, 9, 11, 18, 29, 30; Nice Classification",
    sourceUrl: "https://ipindia.gov.in/trade-marks.htm",
    version: "As amended 2010",
    effectiveDate: "1999-12-30",
    tags: "trademark,brand,registration,ayurveda,nice_classification,generic,descriptive",
  },
  // ===== INDIA - BIOLOGICAL DIVERSITY / ABS =====
  {
    title: "Biological Diversity Act, 2002 (as amended 2023) - Complete overview",
    category: "statute",
    jurisdiction: "india",
    ipType: "abs",
    content: `The Biological Diversity Act, 2002 (amended 2023) and BD Rules 2024 govern access to biological resources and associated traditional knowledge. STRUCTURE: Three-tier system — National Biodiversity Authority (NBA), State Biodiversity Boards (SBBs), Biodiversity Management Committees (BMCs) at local level. KEY PROVISIONS: (1) Section 3: Foreign persons/entities/NRIs require PRIOR APPROVAL from NBA before obtaining biological resources or associated TK for research, commercial utilization, or bio-survey. Penalty: imprisonment up to 5 years, fine up to Rs.10 lakh. (2) Section 4: Transfer results of research to foreign persons — needs NBA approval. (3) Section 5: Collaborative research with foreign institutions — needs NBA approval. (4) Section 6: Indian persons/entities must give PRIOR INTIMATION to SBB before obtaining biological resources for commercial utilization. New in 2023 Amendment: Section 7 now requires only intimation (not approval) for Indian persons accessing biological resources for commercial use. (5) Section 6(1): Anyone seeking ANY IP right based on research/information on Indian biological resources must obtain prior approval from NBA. Non-compliance: IP right not granted or if granted, can be revoked. (6) 2023 AMENDMENT KEY CHANGES: (a) Exempts registered AYUSH practitioners using codified TK; (b) Exempts cultivated medicinal plants (with conditions); (c) Decriminalizes certain offences (civil penalties instead of criminal); (d) Simplifies compliance for Indian users; (e) Promotes Indian systems of medicine; (f) Allows compounding of offences. (7) 2024 RULES: Digital application portal, standardized forms, timeline for decisions (6 months), percentage-based benefit sharing.`,
    citation: "Biological Diversity Act, 2002, Sections 3-7, 18-21, 38-41; BD Amendment Act, 2023; BD Rules, 2024",
    sourceUrl: "http://nbaindia.org",
    version: "2023 Amendment, 2024 Rules",
    effectiveDate: "2024-01-01",
    tags: "abs,biodiversity,biological_resources,nba,sbb,benefit_sharing,traditional_knowledge,2023_amendment,2024_rules",
  },
  {
    title: "ABS Compliance Flow for Ayurvedic Products - Detailed Guide",
    category: "guidance",
    jurisdiction: "india",
    ipType: "abs",
    content: `ACCESS AND BENEFIT SHARING (ABS) COMPLIANCE FLOW: Step 1 - DETERMINE APPLICABILITY: Does your product use biological resources from India? If YES, ABS likely applies. Is the resource cultivated or wild-harvested? Cultivated resources have simplified compliance under 2023 Amendment. Does the product rely on associated traditional knowledge? If YES, additional obligations apply. Step 2 - DETERMINE YOUR CATEGORY: (a) Foreign entity: Requires NBA prior approval under Section 3 — most stringent; (b) Indian entity, commercial use: Prior intimation to SBB under Section 7 (amended); (c) Registered AYUSH practitioner: Exempted for practice using codified TK under 2023 Amendment; (d) Vaids/Hakims using codified TK: Exempted under 2023 Amendment; (e) Academic/research institution (Indian): Prior intimation to concerned SBB. Step 3 - FILE APPLICATION: Use NBA/SBB digital portal → Submit Form I (access) or Form III (IP application). Timeline: NBA should decide within 6 months. Step 4 - BENEFIT SHARING: As per 2024 Rules: 1-3% of ex-factory sale price for access to biological resources; 3-5% for access to TK. Can be monetary (percentage of revenue, upfront payment, milestone payments) or non-monetary (capacity building, technology transfer, joint research, employment of locals). Step 5 - CLEARANCE: Receive approval/acknowledgment certificate → Maintain records → Annual compliance reports. PENALTIES FOR NON-COMPLIANCE: Under original Act: Imprisonment 3-5 years + fine Rs.10 lakh. Under 2023 Amendment: Many offences now carry civil penalties instead of criminal prosecution.`,
    citation: "Biological Diversity Act, 2002 (as amended 2023); BD Rules 2024, Rules 14-17; NBA Guidelines on ABS",
    sourceUrl: "http://nbaindia.org",
    version: "Current",
    effectiveDate: "2024-01-01",
    tags: "abs,compliance,flow,ayurveda,nba,sbb,benefit_sharing,application,penalty",
  },
  {
    title: "NBA Prior Approval for IP Applications - Section 6(1)",
    category: "statute",
    jurisdiction: "india",
    ipType: "abs",
    content: `Section 6(1) of the Biological Diversity Act, 2002 is CRITICAL for any IP filing related to Ayurvedic innovations. It states: "No person shall apply for any intellectual property right, by whatever name called, in or outside India for any invention based on any research or information on a biological resource obtained from India, without obtaining the previous approval of the National Biodiversity Authority before making such application." This means: (1) BEFORE filing a patent, trademark (if based on biological resource), or any other IP right based on Indian biological resources, you MUST get NBA approval; (2) Filing IP application without NBA approval: The IP right shall NOT be granted. If granted, it may be revoked; (3) This applies to both Indian and foreign applicants; (4) The 2023 Amendment has somewhat relaxed this for codified traditional knowledge and cultivated resources, but the fundamental requirement for NBA approval before IP filing remains; (5) FORM III of BD Rules is used for this application; (6) NBA's approval conditions may include benefit-sharing terms; (7) For PCT applications, obtain NBA approval before entering India national phase.`,
    citation: "Biological Diversity Act, 2002, Section 6(1); BD Rules 2024, Form III; NBA Guidelines",
    sourceUrl: "http://nbaindia.org",
    version: "As amended 2023",
    effectiveDate: "2023-08-01",
    tags: "abs,nba,section6,ip_application,patent,approval,mandatory,biological_resource",
  },
  // ===== INDIA - DRUGS & COSMETICS =====
  {
    title: "Drugs and Cosmetics Act, 1940 - Classification of Ayurvedic Products",
    category: "statute",
    jurisdiction: "india",
    ipType: "regulatory",
    content: `The Drugs and Cosmetics Act, 1940 (DCA) classifies Ayurvedic products: (1) CLASSICAL/GENERIC MEDICINE (Rule 158-B read with First Schedule): Formulations described in authoritative texts in the First Schedule — Charaka Samhita, Sushruta Samhita, Ashtanga Hridaya/Sangraha, Sharangdhara Samhita, Bhava Prakasha, Yoga Ratnakara, Rasatarangini, Rasa Ratna Samucchaya, Siddha Yoga Sangraha, Bhaishajya Ratnavali, and 52 other texts. Only manufacturing license required, NO clinical trials. IP status: Largely TK, Section 3(p) bar applies. (2) PATENT/PROPRIETARY MEDICINE (Rule 158-B): NOT in authoritative texts but based on Ayurvedic principles. Proprietary ingredients or novel combinations. Manufacturing license with additional documentation. IP status: Potentially patentable. (3) NEW DRUG (Rule 122-DAB): New formulations or classical formulations for new therapeutic indications. Clinical trials (Phase I-III or as specified) and safety/efficacy data required. IP status: Strongest patent potential. (4) PHYTOPHARMACEUTICAL: Purified plant fractions with clinical evidence. Regulated under D&C Rules Schedule Y. (5) COSMETIC: Products for cleansing, beautifying, promoting attractiveness — regulated under Chapter III of DCA, not Chapter IVA. (6) MANUFACTURING LICENSE: Required under Section 33EEB for ASU drugs, issued by State Licensing Authority. GMP compliance under Schedule T is mandatory.`,
    citation: "Drugs & Cosmetics Act, 1940, Chapters III, IVA; D&C Rules, Rules 158-B, 122-DAB, Schedule T, First Schedule",
    sourceUrl: "https://cdsco.gov.in",
    version: "As amended",
    effectiveDate: "1940-04-10",
    tags: "drugs,cosmetics,classification,classical,proprietary,new_drug,phytopharma,ayurveda,first_schedule,schedule_t",
  },
  {
    title: "First Schedule - Authoritative Ayurvedic Texts",
    category: "statute",
    jurisdiction: "india",
    ipType: "regulatory",
    content: `The First Schedule to the Drugs & Cosmetics Act lists authoritative texts of Ayurveda, Siddha, and Unani systems. AYURVEDIC TEXTS IN FIRST SCHEDULE include: (1) Charaka Samhita (चरक संहिता) — by Maharishi Charaka, foundational text of internal medicine; (2) Sushruta Samhita (सुश्रुत संहिता) — by Acharya Sushruta, foundational text of surgery; (3) Ashtanga Hridaya (अष्टांग हृदय) and Ashtanga Sangraha — by Vagbhata; (4) Sharangdhara Samhita (शारंगधर संहिता) — comprehensive formulary; (5) Bhava Prakasha (भाव प्रकाश) — Bhavamishra's encyclopedic text; (6) Yoga Ratnakara — comprehensive treatment guide; (7) Rasatarangini (रसतरंगिणी) — Rasa Shastra (metallurgy/chemistry) text; (8) Chakradatta — by Chakrapanidatta; (9) Bhaishajya Ratnavali — comprehensive pharmacopoeia; (10) And over 45 other texts. SIGNIFICANCE: Formulations described in these texts are considered 'classical medicines' and can be manufactured with only a manufacturing license (no clinical trials). They are also considered traditional knowledge for patent purposes under Section 3(p). The TKDL database draws heavily from these texts.`,
    citation: "Drugs & Cosmetics Act, 1940, First Schedule; D&C Rules, Rule 158-B",
    sourceUrl: "https://cdsco.gov.in",
    version: "As amended",
    effectiveDate: "1940-04-10",
    tags: "first_schedule,authoritative_texts,charaka,sushruta,vagbhata,sharangdhara,bhava_prakasha,classical,ayurveda",
  },
  {
    title: "Schedule T - GMP for ASU Drugs Manufacturing",
    category: "rule",
    jurisdiction: "india",
    ipType: "regulatory",
    content: `Schedule T of the Drugs & Cosmetics Rules prescribes Good Manufacturing Practices (GMP) for Ayurveda, Siddha, and Unani (ASU) drugs. KEY REQUIREMENTS: (1) PREMISES: Adequate space, clean rooms, separate areas for different operations, pest control, waste disposal; (2) PLANT AND EQUIPMENT: Suitable for ASU drug manufacturing, properly calibrated, maintained; (3) RAW MATERIALS: Authentication of raw materials by qualified persons, proper storage, testing for identity, purity, quality; (4) MANUFACTURING OPERATIONS: Written standard operating procedures (SOPs), batch manufacturing records, in-process controls; (5) QUALITY CONTROL: In-house testing laboratory, pharmacopoeial testing, stability studies; (6) DOCUMENTATION: Batch records, distribution records, complaint handling; (7) PERSONNEL: Qualified technical staff including degree/diploma holders in Ayurveda/Pharmacy; (8) WHO-GMP: India is progressively moving ASU manufacturing towards WHO-GMP standards. Some export-oriented manufacturers voluntarily comply with WHO-GMP. SIGNIFICANCE FOR IP: GMP compliance is a prerequisite for manufacturing license. Non-compliance can result in license cancellation. Quality-controlled manufacturing processes may themselves be protectable as trade secrets.`,
    citation: "D&C Rules, Schedule T; WHO GMP Guidelines for ASU Drugs",
    sourceUrl: "https://cdsco.gov.in",
    version: "As amended",
    effectiveDate: "2000-06-23",
    tags: "gmp,schedule_t,manufacturing,quality_control,asu,ayurveda,siddha,unani",
  },
  {
    title: "Drugs and Magic Remedies (Objectionable Advertisements) Act, 1954",
    category: "statute",
    jurisdiction: "india",
    ipType: "regulatory",
    content: `The DMRA, 1954 regulates advertising of drugs including Ayurvedic medicines. KEY PROVISIONS: (1) Section 3: Prohibits advertising for prevention/cure/treatment of diseases specified in Schedule J (includes cancer, diabetes, heart disease, epilepsy, blindness, etc.); (2) Section 4: Prohibits misleading advertisements — no ads suggesting product has been endorsed by any medical practitioner unless true; (3) Section 5: Prohibits advertisements relating to 'magic remedies' — talismans, mantras, kavachas claiming miraculous remedial properties; (4) Section 7: Penalties — First offence: imprisonment up to 6 months and/or fine; subsequent: imprisonment up to 1 year and/or fine; (5) AYUSH Ministry has issued additional Advertising Guidelines for AYUSH products (2018, updated). PRACTICAL IMPLICATIONS: (a) When marketing trademarked/patented Ayurvedic products, claims must be carefully crafted; (b) Only claims substantiated by evidence are permitted; (c) 'Disease cure' claims for Schedule J diseases are prohibited regardless of evidence; (d) Digital/social media advertisements are also covered; (e) ASCI (Advertising Standards Council of India) guidelines apply additionally. The 2020 COVID-19 period saw increased enforcement against misleading AYUSH product claims.`,
    citation: "DMRA, 1954, Sections 3-7, Schedule J; AYUSH Advertising Guidelines 2018",
    sourceUrl: "https://legislative.gov.in",
    version: "1954 (proposed amendments pending)",
    effectiveDate: "1954-04-30",
    tags: "advertising,drugs,magic_remedies,restrictions,schedule_j,ayurveda,marketing,claims",
  },
  {
    title: "FSSAI Ayurveda-Aahar Regulations 2022",
    category: "rule",
    jurisdiction: "india",
    ipType: "regulatory",
    content: `FSSAI Ayurveda Aahar Regulations, 2022 create a distinct category for Ayurvedic dietary products. KEY PROVISIONS: (1) DEFINITION: 'Ayurveda Aahara' means food products that have a history of use in Ayurveda for promoting health and well-being; (2) ELIGIBLE PRODUCTS: Based on texts like Dravyaguna Vigyana, Ashtanga Hridaya's Annapana Vidhi; includes traditional preparations like Panakam, Mantha, various Lehyas (when marketed as food); (3) REGULATORY PATHWAY: FSSAI license (not drug license) → Compliance with food safety standards → FSSAI labelling → Cannot make therapeutic claims; (4) CLAIMS ALLOWED: Wellness claims, nutritional claims, structure/function claims — NOT disease treatment/prevention claims; (5) LABELLING: Must follow FSSAI labelling regulations, include nutritional information, ingredient list, allergen warnings; (6) STANDARDS: Must comply with FSSAI food safety standards for contaminants (heavy metals, pesticides, aflatoxins), microbiological limits; (7) IMPORTS/EXPORTS: Products must comply with importing country's food regulations. IP IMPLICATIONS: (a) Brand names protectable via trademarks; (b) Unique formulations as trade secrets; (c) Novel processing methods potentially patentable; (d) Packaging designs protectable; (e) Lower regulatory burden than drugs = faster market entry. This category is increasingly popular for AYUSH startups.`,
    citation: "FSS (Ayurveda Aahara) Regulations, 2022; FSS Act, 2006; FSSAI Notifications",
    sourceUrl: "https://fssai.gov.in",
    version: "2022",
    effectiveDate: "2022-07-01",
    tags: "fssai,ayurveda_aahar,food,nutraceutical,labelling,wellness,dietary_supplement,startup",
  },
  // ===== INDIA - OTHER IP =====
  {
    title: "Copyright Protection for Ayurvedic Works",
    category: "statute",
    jurisdiction: "india",
    ipType: "copyright",
    content: `Copyright Act, 1957 protects original works relevant to Ayurveda: (1) ANCIENT TEXTS: Public domain (expired copyright) — but NEW translations, commentaries, compilations with original selection/arrangement, and critical editions attract copyright; (2) RESEARCH: Scientific papers, clinical trial reports, monographs — copyrightable as literary works; (3) SOFTWARE: Diagnostic apps, formulation databases, Ayurvedic practice management software — protected as literary works; (4) ARTISTIC WORKS: Herb illustrations, anatomical drawings, packaging artwork — copyrightable; (5) DATABASES: Original databases with creative selection/arrangement protectable; (6) DURATION: Author's lifetime + 60 years (India); (7) REGISTRATION: Optional but recommended — provides prima facie evidence in court. Register at copyright.gov.in; (8) FAIR USE: Section 52 provides fair dealing exceptions for research, private study, criticism, review. SIGNIFICANCE FOR AYURVEDA: Copyright is often the most straightforward IP protection available for Ayurvedic practitioners — any original written content, illustrations, or software gets automatic protection.`,
    citation: "Copyright Act, 1957, Sections 13, 14, 17, 45, 52; Copyright Rules, 2013",
    sourceUrl: "https://copyright.gov.in",
    version: "As amended 2012",
    effectiveDate: "1957-01-21",
    tags: "copyright,literary,artistic,text,database,software,ayurveda,registration",
  },
  {
    title: "Design Registration for Ayurvedic Products",
    category: "statute",
    jurisdiction: "india",
    ipType: "design",
    content: `Designs Act, 2000 protects novel visual designs. For Ayurveda: (1) PROTECTABLE: Unique bottle/container shapes, packaging configurations, tablet/capsule shapes (if distinctive), label designs, surface ornamentation, device designs (e.g., Panchakarma equipment); (2) REQUIREMENTS: New, original, not previously published, not mere mechanical contrivance, not contrary to public order/morality; (3) REGISTRATION: Application to Controller of Designs, Kolkata → Examination → Registration; (4) DURATION: Initially 10 years, extendable to 15 years; (5) FEES: Rs. 1,000 for individuals, Rs. 4,000 for others; (6) LOCARNO CLASSIFICATION: Class 09 (packaging containers) and Class 24 (medical equipment) most relevant; (7) NOTE: Only aesthetic features protected, NOT functional features; (8) PRIOR ART: Design must not have been published anywhere in the world before filing date. Social media posts can destroy novelty.`,
    citation: "Designs Act, 2000, Sections 2, 4, 5, 11; Designs Rules, 2001; Locarno Classification",
    sourceUrl: "https://ipindia.gov.in/designs.htm",
    version: "2000",
    effectiveDate: "2001-05-11",
    tags: "design,packaging,shape,ornamentation,registration,ayurveda,locarno",
  },
  {
    title: "Plant Variety Protection for Medicinal Plants - PPVFRA",
    category: "statute",
    jurisdiction: "india",
    ipType: "plant_variety",
    content: `Protection of Plant Varieties and Farmers' Rights Act, 2001 (PPVFRA). RELEVANCE TO AYURVEDA: (1) PROTECTABLE: New varieties of medicinal plants developed through breeding — Ashwagandha, Tulsi, Shatavari, Brahmi, Neem, Turmeric, Giloy varieties; (2) CRITERIA: Novelty, Distinctiveness, Uniformity, Stability (DUS testing); (3) CATEGORIES: New variety, Extant variety, Essentially derived variety, Farmers' variety; (4) DURATION: 15 years for crops, 18 years for trees/vines (from date of registration); (5) FARMERS' RIGHTS (Section 39): Farmers can save, use, sow, re-sow, exchange, share, sell farm produce of protected variety (but not sell branded seed); (6) COMMUNITY RIGHTS (Section 41): Communities contributing to variety development have benefit-sharing rights; (7) BENEFIT SHARING (Section 26): Benefit-sharing from commercial exploitation goes to National Gene Fund; (8) REGISTRATION: Application to PPV&FR Authority → DUS testing (2-3 growing seasons) → Registration; (9) FEES: Rs. 2,000 for individuals/farmers, Rs. 5,000 for organizations; (10) KEY INSTITUTION: Protection of Plant Varieties and Farmers' Rights Authority (PPV&FRA), New Delhi. This is distinct from patent protection and GI protection.`,
    citation: "PPVFRA, 2001, Sections 14-18, 26, 39, 41; PPVFR Rules, 2003; PPV&FR Authority",
    sourceUrl: "http://plantauthority.gov.in",
    version: "2001",
    effectiveDate: "2001-10-30",
    tags: "plant_variety,medicinal_plants,farmers_rights,breeding,ashwagandha,tulsi,shatavari,dus",
  },
  {
    title: "Trade Secrets for Ayurvedic Formulations",
    category: "guidance",
    jurisdiction: "india",
    ipType: "trade_secret",
    content: `India has no specific trade secret statute. Protection under common law, contract law, and equity. FOR AYURVEDA: (1) PROTECTABLE AS TRADE SECRETS: Proprietary formulation ratios (exact proportions), processing methods (time, temperature, sequence), quality control parameters, sourcing strategies, customer lists, clinical trial data (before publication); (2) REQUIREMENTS: Information must be secret, have commercial value because of secrecy, reasonable steps taken to maintain secrecy; (3) PROTECTION MECHANISMS: NDAs with employees/contractors/partners, confidentiality clauses in employment contracts, restricted access (physical and digital), encryption, access logs, trade secret policies; (4) TRADE SECRET vs PATENT: Trade secret lasts indefinitely but no protection against independent discovery or reverse engineering. Patent gives 20 years exclusivity but requires full public disclosure. (5) LEGAL BASIS: Indian Contract Act, 1872 (Section 27 — restraint of trade, read with confidentiality obligations); IT Act, 2000 Section 72A (breach of confidentiality); N.R. Dongre v. Whirlpool (1996) — recognized trade secret protection; John Richard Brady v. Chemical Process (1987); Bombay Dyeing v. Mehar Karan Singh (2010). (6) FOR STARTUPS: Trade secrets are often the most cost-effective IP strategy for early-stage Ayurvedic businesses. No registration required, no fees, immediate protection.`,
    citation: "Common law; Indian Contract Act, 1872, Section 27; IT Act, 2000, Section 72A; Case law",
    sourceUrl: "https://legislative.gov.in",
    version: "Current",
    effectiveDate: "Current",
    tags: "trade_secret,formulation,nda,confidentiality,proprietary,ayurveda,startup,cost_effective",
  },
  {
    title: "Digital Personal Data Protection Act, 2023",
    category: "statute",
    jurisdiction: "india",
    ipType: "regulatory",
    content: `DPDPA 2023 governs digital personal data processing. RELEVANCE TO AYUSH PLATFORMS: (1) Any platform handling health queries must comply; (2) KEY PRINCIPLES: Lawfulness, purpose limitation, data minimization, accuracy, storage limitation, security; (3) CONSENT: Informed consent required. Health data requires special attention; (4) DATA PRINCIPAL RIGHTS: Access, correction, erasure, grievance redressal; (5) DATA FIDUCIARY OBLIGATIONS: Security safeguards, breach notification (72 hours to Data Protection Board), Data Protection Officer for significant data fiduciaries; (6) CHILDREN'S DATA: Additional safeguards, verifiable parental consent; (7) CROSS-BORDER TRANSFER: Permitted except to countries restricted by Central Government notification; (8) PENALTIES: Up to Rs. 250 crore for significant breaches; (9) DATA PROTECTION BOARD OF INDIA: Adjudicatory body. FOR IP-SAKTI: User interactions, product details, formulation information must be handled per DPDPA. Consent mechanisms required, data encryption recommended, retention policies needed.`,
    citation: "Digital Personal Data Protection Act, 2023, Sections 4-17; DPDP Rules (draft)",
    sourceUrl: "https://www.meity.gov.in/data-protection-framework",
    version: "2023",
    effectiveDate: "2023-08-11",
    tags: "dpdpa,data_protection,privacy,consent,digital,personal_data,compliance,penalty",
  },
  {
    title: "Ayurvedic Pharmacopoeia of India (API)",
    category: "pharmacopoeia",
    jurisdiction: "india",
    ipType: "regulatory",
    content: `The Ayurvedic Pharmacopoeia of India (API) is the official compendium of standards for Ayurvedic drugs/formulations. Published by Pharmacopoeia Commission for Indian Medicine & Homoeopathy (PCIM&H). KEY ASPECTS: (1) PART I — Single Drugs: Monographs for individual crude drugs (plants, minerals, animal products) with standards for identity, purity, quality; (2) PART II — Formulations: Standards for classical formulations; (3) CONTENTS OF MONOGRAPH: Sanskrit/Hindi/English names, botanical/zoological source, macroscopic/microscopic characters, identity tests (TLC, HPTLC), physico-chemical parameters (ash value, extractive values, moisture content), assay (active constituent quantification), therapeutic uses, dosage; (4) SIGNIFICANCE FOR IP: API standards serve as the quality benchmark for ASU drug manufacturing; compliance with API is mandatory for licensed manufacturers; API monographs can serve as prior art for patent examination; new monographs being added regularly. (5) FORMULARY OF INDIA: Complements API with standardized classical formulations. (6) QUALITY COUNCIL OF INDIA: Involved in quality certification of AYUSH products. (7) NABL ACCREDITATION: Testing labs should be NABL-accredited for API testing.`,
    citation: "Ayurvedic Pharmacopoeia of India, Parts I & II; PCIM&H; D&C Act, Chapter IVA",
    sourceUrl: "https://pcimh.gov.in",
    version: "Current editions",
    effectiveDate: "Ongoing",
    tags: "pharmacopoeia,api,standards,quality,monograph,testing,identity,purity,formulation",
  },
  // ===== INTERNATIONAL =====
  {
    title: "TRIPS Agreement - Traditional Knowledge and Patents",
    category: "treaty",
    jurisdiction: "international",
    ipType: "patent",
    content: `TRIPS Agreement (WTO) sets minimum IP protection standards. FOR AYURVEDA: (1) Article 27.1: Patents available for all inventions meeting novelty, inventive step, industrial application — applies to Ayurvedic innovations meeting these criteria; (2) Article 27.2: Exclusions for ordre public/morality permitted; (3) Article 27.3(b): Members may exclude plants/animals (other than micro-organisms) and essentially biological processes. This is under review — India advocates for mandatory TK disclosure; (4) Article 29: Disclosure sufficient to enable person skilled in art. India pushes for mandatory disclosure of GR/TK origin — not yet in TRIPS; (5) Article 62: Procedures for acquisition/maintenance of IP rights should be reasonable; (6) TRIPS & TK GAP: TRIPS does NOT mandate TK protection. India, African Group, Brazil lead calls for: (a) Mandatory disclosure of origin of GR/TK in patent applications; (b) Prior informed consent evidence; (c) Benefit-sharing evidence; (7) DOHA DECLARATION (2001): Recognized relationship between TRIPS and CBD; (8) TRIPS COUNCIL: Ongoing discussions on GR/TK disclosure amendment. India's position: amend Article 29 to include mandatory disclosure.`,
    citation: "TRIPS Agreement, Articles 27-29, 62; WTO Doha Declaration, 2001, Para 19; TRIPS Council Documents",
    sourceUrl: "https://www.wto.org/english/docs_e/legal_e/27-trips.pdf",
    version: "1994 (ongoing amendments proposed)",
    effectiveDate: "1995-01-01",
    tags: "trips,wto,patent,traditional_knowledge,disclosure,international,doha,amendment",
  },
  {
    title: "Convention on Biological Diversity (CBD) & Nagoya Protocol - Complete Overview",
    category: "treaty",
    jurisdiction: "international",
    ipType: "abs",
    content: `CBD (1992) and Nagoya Protocol (2010) — international ABS framework. CBD: (1) Article 1: Objectives — conservation, sustainable use, fair benefit-sharing; (2) Article 3: Sovereign rights over natural resources; (3) Article 8(j): Respect, preserve, maintain TK of indigenous/local communities; promote benefit-sharing from TK use; (4) Article 15: Access to genetic resources subject to Prior Informed Consent (PIC) and Mutually Agreed Terms (MAT); (5) Article 16: Technology transfer. NAGOYA PROTOCOL (2010, in force 2014): (1) Article 5: Fair and equitable benefit-sharing from utilization of GR; (2) Article 6: Access to GR subject to PIC and MAT from providing country; (3) Article 7: Access to TK associated with GR — PIC/approval from indigenous communities; (4) Article 12: TK associated with GR — community protocols; (5) Articles 15-16: Compliance measures — user countries must ensure their nationals comply with providing country's ABS laws; (6) Article 17: Monitoring — checkpoints (patent offices, regulatory agencies) for compliance; (7) ABS CLEARING HOUSE: Global database of national ABS laws, permits. KEY USER-COUNTRY IMPLEMENTATIONS: EU Regulation 511/2014 (due diligence), Switzerland (Federal Act), Japan (Guidelines), South Korea (Act on ABS). FOR AYURVEDIC EXPORTS: Must comply with BOTH India's BD Act AND destination country's Nagoya Protocol implementation.`,
    citation: "CBD, 1992, Articles 1, 3, 8(j), 15, 16; Nagoya Protocol, 2010, Articles 5-7, 12, 15-17",
    sourceUrl: "https://www.cbd.int",
    version: "CBD 1992, Nagoya 2010",
    effectiveDate: "1993-12-29",
    tags: "cbd,nagoya,abs,benefit_sharing,genetic_resources,traditional_knowledge,pic,mat,compliance",
  },
  {
    title: "WIPO Treaty on Genetic Resources and Associated Traditional Knowledge (2024)",
    category: "treaty",
    jurisdiction: "international",
    ipType: "patent",
    content: `WIPO GRATK Treaty, adopted May 2024 at the Diplomatic Conference in Geneva — landmark achievement after 20+ years of negotiations. KEY PROVISIONS: (1) Article 3 — MANDATORY DISCLOSURE: Patent applicants MUST disclose country of origin or source of genetic resources (GR) when claimed invention is materially based on GR; (2) Article 4 — TK DISCLOSURE: When invention materially based on TK associated with GR, applicants must disclose the indigenous peoples/local community that provided TK, where possible; (3) Article 5 — SANCTIONS: Non-compliance may result in: application deemed withdrawn, post-grant administrative revocation, fines, other remedies as per national law; (4) Article 6 — NO IMPACT ON VALIDITY: Non-disclosure alone does not invalidate a granted patent (but national law may provide otherwise); (5) Article 7 — INFORMATION SYSTEMS: Parties shall establish/maintain databases and information systems for GR/TK; (6) SIGNIFICANCE FOR AYURVEDA: (a) Creates first binding international obligation to disclose TK sources in patent applications; (b) Complements India's domestic requirements under BD Act Section 6(1); (c) Helps prevent biopiracy by increasing transparency; (d) Strengthens TKDL's role globally; (e) India championed this treaty for decades; (7) STATUS: Open for signature. Not yet in force — requires ratification by member states; (8) IMPLEMENTATION: Countries will need to amend patent laws to include disclosure requirements.`,
    citation: "WIPO Treaty on IP, Genetic Resources and Associated TK, 2024, Articles 3-7",
    sourceUrl: "https://www.wipo.int/diplomatic-conferences/en/genetic-resources/",
    version: "2024",
    effectiveDate: "2024-05-24",
    tags: "wipo,gratk,treaty,disclosure,genetic_resources,traditional_knowledge,2024,patent,biopiracy",
  },
  {
    title: "PCT - International Patent Filing for Ayurvedic Innovations",
    category: "treaty",
    jurisdiction: "international",
    ipType: "patent",
    content: `Patent Cooperation Treaty (PCT) — unified international patent filing. FOR AYURVEDIC INNOVATORS: (1) SINGLE APPLICATION: Designating up to 157 countries; (2) TIMELINE: 30-31 months from priority date to enter national phase (vs. 12 months Paris Convention); (3) PROCESS: File PCT at Indian Patent Office (Receiving Office) → International Search Authority (ISA — typically Indian PO or EPO) → International Search Report (ISR) + Written Opinion → Optional Chapter II (International Preliminary Examination) → National Phase entry in chosen countries; (4) FEES: Reduced for applicants from India. Individual inventors/startups get further reductions. Total PCT phase: approximately Rs. 1-3 lakh; (5) STRATEGY: File first in India (priority application) → PCT within 12 months → Use ISR to assess global patentability → Enter national phase selectively in key markets (US, EU, Japan, China, ASEAN, Australia); (6) KEY MARKETS FOR AYURVEDA: USA (largest market), EU (growing), Japan (kampo/herbal market), Australia, ASEAN (Thailand, Singapore, Malaysia), South Korea; (7) NATIONAL PHASE CONSIDERATIONS: Each country examines under its own patent law. Section 3(p) bar is India-specific. Other countries may be more amenable to TK-based inventions — but WIPO GRATK Treaty will change this; (8) PATENT PROSECUTION HIGHWAY (PPH): Agreements between patent offices for expedited examination. Indian PO has PPH with JPO, KIPO.`,
    citation: "PCT, 1970, Articles 3-11; PCT Regulations; PCT Applicant's Guide; WIPO Fee Tables",
    sourceUrl: "https://www.wipo.int/pct/en/",
    version: "As amended",
    effectiveDate: "1978-01-24",
    tags: "pct,international_patent,filing,national_phase,ayurveda,wipo,strategy,fees",
  },
  {
    title: "Madrid System - International Trademark Registration",
    category: "treaty",
    jurisdiction: "international",
    ipType: "trademark",
    content: `Madrid Protocol — centralized international trademark registration. FOR AYURVEDIC BRANDS: (1) FILE: Through Indian TM Registry → WIPO International Bureau → Designated countries; (2) COVERAGE: 130+ countries. Key Ayurveda export markets: USA, EU, UK, Japan, Australia, Singapore, Thailand, South Korea, Canada, UAE; (3) PROCESS: Indian base application/registration → Madrid application (Form MM2) → WIPO examination → Notification to designated offices → National examination (12-18 months); (4) FEES: Base fee (653 CHF) + supplementary fee per designated country. Total varies by number of designations; (5) DURATION: 10 years, renewable; (6) ADVANTAGES: Single application, one set of fees, centralized management, single renewal; (7) CHALLENGES FOR AYURVEDIC BRANDS: (a) Sanskrit/Hindi names may face distinctiveness issues abroad; (b) Ayurvedic terms may be generic in certain markets; (c) Transliteration challenges; (d) Need for use evidence in some countries (e.g., US requires actual use); (8) STRATEGY: Secure Indian TM first → File Madrid for top 5-10 export markets → Monitor → Enforce. Consider registering in local languages for key markets.`,
    citation: "Madrid Protocol, 1989, Articles 2-5; Common Regulations; WIPO Madrid Guide",
    sourceUrl: "https://www.wipo.int/madrid/en/",
    version: "As amended",
    effectiveDate: "2013-04-08",
    tags: "madrid,trademark,international,brand,registration,export,ayurveda,wipo",
  },
  {
    title: "Hague System - International Design Registration",
    category: "treaty",
    jurisdiction: "international",
    ipType: "design",
    content: `Hague Agreement — international industrial design registration. India joined 2019. FOR AYURVEDIC PRODUCTS: (1) Single application with WIPO → Protection in 90+ designated countries; (2) Up to 100 designs per application (same Locarno class); (3) Relevant for: packaging, containers, medical devices, product shapes, labels; (4) DURATION: 5 years, renewable to 15 years (varies by country); (5) FEES: Relatively modest — base fee + per-design + per-designation; (6) STRATEGY: File Indian design first → Hague for export markets within 6 months (priority). Focus on distinctive, non-functional visual features of packaging.`,
    citation: "Hague Agreement, Geneva Act 1999; India's accession 2019",
    sourceUrl: "https://www.wipo.int/hague/en/",
    version: "Geneva Act 1999",
    effectiveDate: "2019-11-02",
    tags: "hague,design,international,packaging,registration,wipo,india",
  },
  {
    title: "Budapest Treaty - Micro-organism Deposits for Ayurvedic Biotech",
    category: "treaty",
    jurisdiction: "international",
    ipType: "patent",
    content: `Budapest Treaty — international recognition of micro-organism deposits for patent purposes. RELEVANCE TO AYURVEDA: (1) Required when patent involves micro-organism not adequately described in writing; (2) AYURVEDIC APPLICATIONS: Probiotic strains from traditional fermented preparations (Asavas, Arishtas, fermented rice), biocontrol agents for medicinal plant cultivation, endophytic fungi from medicinal plants, novel microbial strains with therapeutic properties; (3) INDIAN IDAs: Microbial Type Culture Collection (MTCC) at IMTECH Chandigarh, Microbial Culture Collection (MCC) at NCMR Pune; (4) Single deposit recognized by all 85+ member states; (5) Deposit must be made before or on patent filing date; (6) Sample accessible to public after patent publication.`,
    citation: "Budapest Treaty, 1977, Articles 3-7; MTCC; MCC, Pune",
    sourceUrl: "https://www.wipo.int/budapest/en/",
    version: "1977 (as amended 1980)",
    effectiveDate: "1980-08-19",
    tags: "budapest,microorganism,deposit,biotech,fermented,asava,arishta,probiotic,endophytic",
  },
  {
    title: "EU Herbal Medicinal Products Directive - Market Access",
    category: "rule",
    jurisdiction: "international",
    ipType: "regulatory",
    content: `EU Directive 2004/24/EC and 2001/83/EC — EU market access for herbal/Ayurvedic products. KEY REQUIREMENTS: (1) TRADITIONAL USE REGISTRATION (TUR): For products with 30+ years traditional use (15+ years in EU). Simplified registration, no clinical trials required. Bibliographic evidence sufficient. (2) FULL MARKETING AUTHORIZATION: Without sufficient traditional use evidence, full clinical dossier required. Very expensive (millions of euros). (3) FOOD SUPPLEMENT: If no therapeutic claims, can enter as food supplement under EU Food Supplement Directive 2002/46/EC. Lower barrier but no therapeutic claims. (4) QUALITY: EU GMP (Directive 2003/94/EC), European Pharmacopoeia monographs, strict limits on heavy metals (cadmium <1 ppm, lead <5 ppm, mercury <0.1 ppm), pesticide residues, aflatoxins, microbiological limits; (5) CHALLENGES FOR AYURVEDA: Multi-ingredient formulations face complex requirements; limited EU pharmacopoeia monographs for Indian herbs; 15-year EU use requirement difficult; Rasa Shastra (metallic) preparations face severe restrictions; (6) EU ABS REGULATION 511/2014: Due diligence obligations for users of GR and associated TK under Nagoya Protocol. Declarations of due diligence required. IP CONSIDERATIONS: Data exclusivity for clinical data, TM via Madrid or direct filing, regulatory data protection.`,
    citation: "EU Directives 2004/24/EC, 2001/83/EC, 2002/46/EC; EU Regulation 511/2014; European Pharmacopoeia",
    sourceUrl: "https://eur-lex.europa.eu",
    version: "Current",
    effectiveDate: "2011-04-30",
    tags: "eu,herbal,market_access,traditional_use,registration,quality,export,ayurveda,heavy_metals",
  },
  {
    title: "US FDA Dietary Supplement Regulations for Ayurvedic Products",
    category: "rule",
    jurisdiction: "international",
    ipType: "regulatory",
    content: `US FDA regulation of Ayurvedic products — primarily as dietary supplements. KEY FRAMEWORK: (1) DSHEA 1994: Most Ayurvedic products enter US as dietary supplements. No pre-market approval, but manufacturer responsible for safety/label accuracy; (2) STRUCTURE/FUNCTION CLAIMS: Can claim effect on body structure/function (e.g., "supports immune health") but CANNOT claim to diagnose, treat, cure, prevent disease. Must include disclaimer: "This statement has not been evaluated by the FDA. This product is not intended to diagnose, treat, cure, or prevent any disease."; (3) NEW DIETARY INGREDIENT (NDI): If ingredient not marketed before Oct 15, 1994, NDI notification to FDA required 75 days before marketing. Many Indian herbs may require NDI notification; (4) cGMP: 21 CFR Part 111 compliance mandatory; (5) LABELING: Supplement Facts panel, ingredient list with botanical names, part used; (6) ADULTERATION: FDA can take action against adulterated/misbranded products. FDA has issued import alerts for Ayurvedic products containing undeclared ingredients, heavy metals; (7) GRAS: Some ingredients may qualify for Generally Recognized As Safe status for food use; (8) US PATENT STRATEGY: No Section 3(p) equivalent. Ayurvedic formulations MAY be patentable in US even if TK in India. But TKDL access agreement with USPTO helps. File US provisional patent early. (9) FTC: Federal Trade Commission regulates advertising claims separately. Substantiation required for all claims.`,
    citation: "DSHEA, 1994; 21 CFR Part 111; FDA Guidance Documents; FTC Act",
    sourceUrl: "https://www.fda.gov/food/dietary-supplements",
    version: "Current",
    effectiveDate: "1994-10-25",
    tags: "us,fda,dietary_supplement,dshea,market_access,labeling,ndi,export,ayurveda,patent,ftc",
  },
  {
    title: "Japan - Kampo and Herbal Product Regulations",
    category: "rule",
    jurisdiction: "international",
    ipType: "regulatory",
    content: `Japan's regulatory framework for herbal/traditional medicine products. KEY ASPECTS: (1) KAMPO SYSTEM: Japan has its own codified traditional medicine system (Kampo) with 148 approved formulations under national health insurance; (2) REGULATORY CATEGORIES: (a) OTC Kampo products — standardized formulations, no prescription needed; (b) Ethical Kampo — prescription required; (c) Dietary supplements (Health Foods) — includes 'Foods with Function Claims' and 'Foods for Specified Health Uses (FOSHU)'; (3) FOR AYURVEDIC PRODUCTS: Most enter as dietary supplements or health foods. FOSHU approval (clinical evidence required) enables health claims but is expensive; 'Foods with Function Claims' — notification-based, systematic review sufficient; (4) IP IN JAPAN: Japan Patent Office (JPO) is receptive to herbal composition patents. PCT national phase entry through JPO. Strong TM protection via Madrid; (5) CHALLENGES: Language barrier, different quality standards (Japanese Pharmacopoeia), regulatory requirements for heavy metals/pesticides more stringent than India.`,
    citation: "Japan Pharmaceutical Affairs Act; Japanese Pharmacopoeia; FOSHU Guidelines; JPO Patent Guidelines",
    sourceUrl: "https://www.mhlw.go.jp",
    version: "Current",
    effectiveDate: "Current",
    tags: "japan,kampo,herbal,market_access,foshu,dietary_supplement,patent,ayurveda,export",
  },
  {
    title: "ASEAN Harmonization for Traditional Medicines",
    category: "rule",
    jurisdiction: "international",
    ipType: "regulatory",
    content: `ASEAN Traditional Medicine regulations — key export market for Ayurveda. KEY ASPECTS: (1) ASEAN TMHS: Traditional Medicines and Health Supplements (TMHS) Working Group working on harmonization; (2) COUNTRY-SPECIFIC REGULATIONS: (a) Singapore — Health Supplements under HSA, TM products under Chinese Proprietary Medicine framework, Ayurvedic products require specific evaluation; (b) Thailand — FDA Thailand regulates traditional medicines, strong domestic traditional medicine framework (Thai Traditional Medicine); (c) Malaysia — NPRA registers traditional products, requires safety/quality data, GMP compliance; (d) Indonesia — BPOM regulates traditional medicines (Jamu), three categories based on evidence level; (3) COMMON REQUIREMENTS: Quality standards, safety data, GMP compliance, proper labelling in local language, no prohibited ingredients; (4) IP STRATEGY FOR ASEAN: File trademarks via Madrid in key ASEAN countries; PCT national phase for patents; consider local partnerships; (5) GROWING MARKET: ASEAN herbal/traditional medicine market is growing rapidly, cultural acceptance of traditional medicine is high, India-ASEAN trade agreements provide tariff advantages.`,
    citation: "ASEAN TMHS Guidelines; Country-specific regulations; India-ASEAN FTA",
    sourceUrl: "https://asean.org",
    version: "Current",
    effectiveDate: "Current",
    tags: "asean,traditional_medicine,export,singapore,thailand,malaysia,indonesia,market_access",
  },
  {
    title: "WHO Traditional Medicine Strategy 2014-2023 (extended)",
    category: "guidance",
    jurisdiction: "international",
    ipType: "regulatory",
    content: `WHO Traditional Medicine Strategy provides the international framework. KEY ELEMENTS: (1) OBJECTIVES: Integrate traditional medicine (TM) into health systems, promote safety/efficacy/quality, increase access; (2) REGULATION: WHO recommends national regulatory frameworks for TM products; encourages monograph development; supports pharmacovigilance for TM; (3) QUALITY: WHO Guidelines on Good Agricultural and Collection Practices (GACP) for medicinal plants; WHO Guidelines on GMP for herbal medicines; (4) SAFETY: WHO Guidelines on safety monitoring of herbal medicines; (5) INTEGRATION: WHO encourages integration of TM into primary healthcare; (6) IP IMPLICATIONS: WHO recognizes need to protect TK from misappropriation; supports documentation of TK; encourages benefit-sharing; (7) WHO HERBAL MONOGRAPHS: WHO publishes monographs for medicinal plants — useful as quality references and can serve as evidence for safety/traditional use in regulatory submissions; (8) INTERNATIONAL REGULATORY COOPERATION (IRC): WHO facilitates cooperation between national regulatory authorities for TM products; (9) ICD-11: International Classification of Diseases now includes a Traditional Medicine module.`,
    citation: "WHO Traditional Medicine Strategy 2014-2023; WHO Guidelines on GACP, GMP; WHO Herbal Monographs",
    sourceUrl: "https://www.who.int/traditional-complementary-integrative-medicine",
    version: "2014-2023 (extended)",
    effectiveDate: "2014-01-01",
    tags: "who,traditional_medicine,strategy,quality,safety,gacp,gmp,monograph,integration",
  },
  {
    title: "Export of AYUSH Products - Comprehensive Regulatory Guide",
    category: "guidance",
    jurisdiction: "international",
    ipType: "regulatory",
    content: `COMPREHENSIVE GUIDE FOR EXPORTING AYURVEDIC PRODUCTS: (1) INDIAN EXPORT REQUIREMENTS: (a) Drug export license from State Drug Controller; (b) AYUSH Product Registration Certificate; (c) Certificate of Pharmaceutical Product (CoPP) from CDSCO for some countries; (d) Free Sale Certificate; (e) GMP certificate; (f) NBA/SBB clearance if using Indian biological resources; (g) APEDA registration for agricultural/herbal exports; (h) DGFT IEC code. (2) KEY EXPORT MARKETS & REQUIREMENTS: USA (DSHEA compliance, FDA facility registration, NDI if applicable), EU (Traditional Use Registration or food supplement), Japan (FOSHU/Foods with Function Claims), Australia (TGA Listed Medicine), Canada (NHP License). (3) IP STRATEGY FOR EXPORTS: File trademarks in target countries BEFORE exporting (via Madrid); consider PCT for patentable innovations; protect trade secrets through NDAs with foreign distributors; register designs for packaging in key markets via Hague. (4) COMMON CHALLENGES: Heavy metal limits (different standards in different countries), pesticide residue limits, labelling requirements (local language, specific warnings), banned ingredients (e.g., certain herbs banned in some countries), shelf life requirements. (5) SUPPORT: Export Promotion Council for AYUSH (set up by Ministry of AYUSH and Ministry of Commerce), PHARMEXCIL, Indian trade missions abroad.`,
    citation: "AYUSH Export Promotion Scheme; DGFT Guidelines; Country-specific regulations",
    sourceUrl: "https://ayush.gov.in",
    version: "Current",
    effectiveDate: "Current",
    tags: "export,ayush,products,regulatory,guide,usa,eu,japan,australia,ip_strategy,trademark,patent",
  },
  {
    title: "Patenting Ayurvedic Innovations Abroad - Strategy and Considerations",
    category: "guidance",
    jurisdiction: "international",
    ipType: "patent",
    content: `STRATEGIC GUIDE FOR INTERNATIONAL PATENTING OF AYURVEDIC INNOVATIONS: (1) PATENTABILITY LANDSCAPE: India (strict — Section 3(p), 3(d) bars for TK); US (more receptive — no specific TK bar, but 35 USC 102/103 novelty/obviousness apply); EU (EPO receptive to novel herbal compositions with data); Japan (JPO receptive, especially with pharmacological data); China (CNIPA — growing acceptance of TCM/herbal patents). (2) WHAT'S PATENTABLE ABROAD: Novel extraction methods, novel drug delivery systems (nanoformulations, liposomal, transdermal), synergistic combinations with pharmacological evidence, new therapeutic indications with clinical data, bioavailability-enhanced formulations, standardized extracts with novel quality markers. (3) FILING STRATEGY: India first filing → PCT application → Selective national phase entry. Consider provisional patent filing for early priority date. (4) DISCLOSURE CONSIDERATIONS: WIPO GRATK Treaty (2024) will require GR/TK disclosure globally once implemented. Proactively disclose to strengthen application. (5) COSTS: PCT + national phase in 5 countries: approximately Rs. 20-40 lakh over 3-5 years. Startups can use government schemes (SIPP, Patent Facilitation Program) for subsidies. (6) TKDL IMPACT: TKDL agreements with foreign patent offices mean classical formulations will be found as prior art. Focus claims on truly novel aspects.`,
    citation: "PCT; 35 USC 102, 103; EPC Articles 52-57; WIPO GRATK Treaty 2024; India Patent Rules 2024",
    sourceUrl: "https://www.wipo.int",
    version: "Current",
    effectiveDate: "Current",
    tags: "patent,international,strategy,us,eu,japan,china,novel,extraction,delivery,synergy,tkdl",
  },
  {
    title: "India's National IPR Policy 2016 and AYUSH IP Support",
    category: "guidance",
    jurisdiction: "india",
    ipType: "patent",
    content: `India's National IPR Policy (2016) and government support for AYUSH IP. KEY ELEMENTS: (1) NATIONAL IPR POLICY 2016: Objective 1 — IP awareness and promotion, including for AYUSH sector; Objective 4 — Modernization of IP administration; Objective 7 — Enforcement. (2) GOVERNMENT SCHEMES FOR AYUSH IP: (a) Scheme for IP Protection and Promotion (SIPP) — subsidized patent filing for startups; (b) Start-up Intellectual Property Protection (SIPP) — 80% fee reduction for startups; (c) AYUSH Research Portal — facilitates research collaboration; (d) National AYUSH Mission — includes support for quality and standardization; (e) AYUSH Start-up Challenge — AYUSH Ministry initiative for innovation; (f) NMPB (National Medicinal Plants Board) — supports cultivation, marketing of medicinal plants. (3) IP FACILITATION CENTRES: TIC (Technology Information, Forecasting and Assessment Council), CIPAM (Cell for IPR Promotion and Management), NIPAM (National Intellectual Property Awareness Mission). (4) FEE CONCESSIONS: Startups — 80% reduction in patent/TM/design fees; small entities — 50% reduction; educational institutions — reduced fees. (5) EXPEDITED EXAMINATION: Available for startups, women applicants, and MSME category.`,
    citation: "National IPR Policy, 2016; SIPP Scheme; Patent Rules 2024; AYUSH Mission Guidelines",
    sourceUrl: "https://dpiit.gov.in/policies-rules-and-acts/national-ipr-policy",
    version: "2016 (ongoing implementation)",
    effectiveDate: "2016-05-12",
    tags: "national_ipr_policy,ayush,startup,sipp,fee_reduction,facilitation,government_support",
  },
  // ===== EXPANDED: CASE LAW =====
  {
    title: "Novartis AG v. Union of India (2013) - Section 3(d) Landmark",
    category: "case_law",
    jurisdiction: "india",
    ipType: "patent",
    content: `Supreme Court of India, Civil Appeal Nos. 2706-2716 of 2013. FACTS: Novartis sought patent for beta-crystalline form of imatinib mesylate (Glivec). The Controller and IPAB rejected the application under Section 3(d). HELD: (1) Section 3(d) bars patents for new forms of known substances unless they show significantly enhanced therapeutic efficacy; (2) "Efficacy" in the context of pharmaceutical products means therapeutic efficacy; (3) Mere improvement in bioavailability, thermodynamic stability, or flow properties is NOT sufficient to show enhanced efficacy; (4) The test is strict: the applicant must show a real advantage in therapeutic terms. SIGNIFICANCE FOR AYURVEDA: If you create a new form of a known Ayurvedic substance (e.g., nano-ashwagandha, liposomal curcumin), you must demonstrate enhanced therapeutic efficacy, not just improved physical properties. This is the most important Supreme Court case for pharmaceutical patentability in India.`,
    citation: "Novartis AG v. Union of India, (2013) 6 SCC 1; Civil Appeal Nos. 2706-2716/2013",
    sourceUrl: "https://www.sci.gov.in",
    version: "2013",
    effectiveDate: "2013-04-01",
    tags: "case_law,novartis,section_3d,efficacy,supreme_court,pharmaceutical,new_form,patent",
    authorityLevel: "primary",
  },
  {
    title: "Biswamohan Mohanty v. Union of India (2014) - Biodiversity Act & TK",
    category: "case_law",
    jurisdiction: "india",
    ipType: "abs",
    content: `National Green Tribunal case regarding access to biological resources and traditional knowledge. KEY HOLDING: The Biological Diversity Act creates a three-tier system (NBA, SBB, BMC) and each has distinct jurisdiction. Individuals and companies cannot bypass these requirements. ABS compliance is mandatory before commercializing products based on Indian biological resources. The case reinforced that non-compliance with the BD Act can lead to criminal penalties including imprisonment. SIGNIFICANCE: Established judicial precedent that the BD Act is strictly enforceable, not merely advisory.`,
    citation: "Biswamohan Mohanty v. Union of India, NGT Original Application No. 26/2012(THC)",
    sourceUrl: "https://greentribunal.gov.in",
    version: "2014",
    effectiveDate: "2014-01-01",
    tags: "case_law,biodiversity,abs,ngt,enforcement,traditional_knowledge,nba,penalty",
    authorityLevel: "primary",
  },
  // ===== EXPANDED: REGISTRY / PROCEDURAL =====
  {
    title: "Patent Filing Procedure - Step-by-Step for AYUSH Innovations",
    category: "guidance",
    jurisdiction: "india",
    ipType: "patent",
    content: `COMPLETE PATENT FILING PROCEDURE FOR AYUSH INNOVATIONS: Step 1: PRIOR ART SEARCH — Search Indian Patent Office database (ipindiaservices.gov.in/publicsearch), Espacenet, Google Patents, PubMed, and request TKDL check if traditional knowledge is involved. Step 2: DRAFTING — Prepare provisional or complete specification with claims. For Ayurvedic inventions, emphasize what is novel beyond TK. Include experimental data showing inventive step. Step 3: FILE APPLICATION — File Form 1 (application), Form 2 (specification), Form 3 (statement of undertaking), Form 5 (declaration of inventorship). Declare biological material source. Declare TK source if applicable. Step 4: PUBLICATION — Application published 18 months from priority date (or earlier on request with Form 9). Step 5: EXAMINATION — Request examination within 48 months (Form 18). For startups, request expedited examination (Form 18A). Step 6: FIRST EXAMINATION REPORT (FER) — Respond within 6 months. Controller may raise Section 3(d), 3(e), 3(p) objections for Ayurvedic inventions. Step 7: HEARING — If objections persist, attend hearing. Step 8: GRANT — If all requirements met, patent granted for 20 years from filing. Step 9: RENEWAL — Pay annual renewal fees (Forms 4). FEES: Individual/startup: Rs. 1,600 (e-filing). Small entity: Rs. 4,000. Others: Rs. 8,000.`,
    citation: "Patents Act, 1970; Patent Rules, 2024; IP India Portal ipindiaonline.gov.in",
    sourceUrl: "https://ipindia.gov.in",
    version: "2024 Rules",
    effectiveDate: "2024-03-15",
    tags: "patent,filing,procedure,step_by_step,form,examination,startup,expedited,fees,ayush",
    authorityLevel: "secondary",
  },
  {
    title: "Trademark Registration Procedure for AYUSH Brands",
    category: "guidance",
    jurisdiction: "india",
    ipType: "trademark",
    content: `TRADEMARK REGISTRATION FOR AYUSH BRANDS: Step 1: CLEARANCE SEARCH — Search TM registry (ipindiaservices.gov.in/tmrpublicsearch) for conflicting marks. Check phonetic, visual, and conceptual similarity. Step 2: CHOOSE CLASS — Class 5 for pharmaceuticals/medicines, Class 3 for cosmetics/soaps, Class 29-30 for food products, Class 44 for medical services. Step 3: FILE APPLICATION — Form TM-A (online at ipindiaonline.gov.in). Include logo/wordmark, goods/services description, applicant details. Step 4: EXAMINATION — Vienna codification for device marks. Examiner checks absolute and relative grounds (Sections 9, 11). Step 5: SHOW CAUSE HEARING — If objections raised, respond within 1 month. Step 6: PUBLICATION — Published in Trade Marks Journal. Step 7: OPPOSITION — 4-month opposition period. Third parties can oppose under Section 21. Step 8: REGISTRATION — Certificate issued. Valid 10 years, renewable. FEES: Individual/startup: Rs. 4,500 (e-filing). Others: Rs. 9,000. TIPS FOR AYUSH: Avoid generic Ayurvedic terms as marks. Create distinctive coined words. Consider filing logo + wordmark separately.`,
    citation: "Trade Marks Act, 1999; TM Rules, 2017; IP India Portal",
    sourceUrl: "https://ipindia.gov.in/trade-marks.htm",
    version: "Current",
    effectiveDate: "2017-03-06",
    tags: "trademark,registration,procedure,step_by_step,form,class_5,class_3,fees,ayush,brand",
    authorityLevel: "secondary",
  },
  // ===== EXPANDED: EXPORT MARKET SPECIFIC =====
  {
    title: "Australia TGA - Complementary Medicines Registration for Ayurveda",
    category: "rule",
    jurisdiction: "international",
    ipType: "regulatory",
    content: `Australia's Therapeutic Goods Administration (TGA) regulates Ayurvedic products as Complementary Medicines. TWO PATHWAYS: (1) LISTED MEDICINE (AUST L): Lower risk, self-assessed for quality/safety. Must comply with TGO 102 (quality standards). Permitted ingredients only (listed in ARTG). No pre-approval clinical trials. Manufacturing must comply with cGMP (PIC/S). Can make limited indications from approved list. (2) REGISTERED MEDICINE (AUST R): Higher risk or higher-level claims. Requires full evaluation including clinical evidence. Much more expensive and time-consuming. IMPORT REQUIREMENTS: Products must be manufactured at TGA-approved or MRA-recognized facilities. Indian GMP (Schedule T) may not be sufficient — PIC/S GMP required. Heavy metals limits: arsenic <5 ppm, cadmium <0.3 ppm, lead <10 ppm, mercury <0.5 ppm. Sponsor must be an Australian entity.`,
    citation: "Therapeutic Goods Act 1989 (Australia); TGO 102; PIC/S GMP Guide; TGA Listed Medicines assessment",
    sourceUrl: "https://www.tga.gov.au",
    version: "Current",
    effectiveDate: "Current",
    tags: "australia,tga,complementary,listed,registered,gmp,export,ayurveda,heavy_metals,market_access",
    authorityLevel: "secondary",
  },
  {
    title: "Canada NHP License for Ayurvedic Products",
    category: "rule",
    jurisdiction: "international",
    ipType: "regulatory",
    content: `Health Canada regulates Ayurvedic products as Natural Health Products (NHPs) under the Natural Health Products Regulations (NHPR). KEY REQUIREMENTS: (1) PRODUCT LICENSE: Apply through Natural and Non-prescription Health Products Directorate (NNHPD). Submit Product License Application (PLA). Evidence of safety and efficacy required — can use traditional use evidence for products with 50+ years of use. (2) SITE LICENSE: Manufacturing site must hold a Health Canada site license or equivalent recognized certification. (3) QUALITY: Good Manufacturing Practices per NHP Regulations Part 3. Specifications for identity, purity, potency. Stability testing. (4) LABELING: Must comply with NHPR labeling requirements. Bilingual (English/French) required. NPN (Natural Product Number) must be displayed. (5) CLAIMS: Can make health claims supported by evidence. Traditional use claims accepted. (6) IP STRATEGY: File trademark through Madrid or directly with CIPO. Consider Canadian patent filing through PCT national phase.`,
    citation: "Natural Health Products Regulations (Canada); Food and Drugs Act (Canada); NNHPD guidance",
    sourceUrl: "https://www.canada.ca/en/health-canada/services/drugs-health-products/natural-non-prescription.html",
    version: "Current",
    effectiveDate: "2004-01-01",
    tags: "canada,nhp,natural_health_product,license,gmp,export,ayurveda,market_access,traditional_use",
    authorityLevel: "secondary",
  },
  // ===== EXPANDED: DETAILED STATUTORY PROVISIONS =====
  {
    title: "Section 25 - Opposition Proceedings for Ayurvedic Patents",
    category: "statute",
    jurisdiction: "india",
    ipType: "patent",
    content: `Section 25 of the Patents Act provides for opposition to patent grant. (1) PRE-GRANT OPPOSITION (Section 25(1)): Any person can file after patent application is published but before grant. Grounds include: (a) wrongly obtained invention; (b) prior publication; (c) prior claiming; (d) prior public knowledge/use in India; (e) obviousness; (f) not an invention under Section 3 (including 3(p) for TK); (g) insufficient description; (h) non-disclosure of information under Section 8; (i) convention application not filed within 12 months. (2) POST-GRANT OPPOSITION (Section 25(2)): Any interested person within 12 months of publication of grant. Same grounds. SIGNIFICANCE FOR AYURVEDA: This is the primary mechanism to challenge wrongful patents on traditional knowledge. TKDL-based evidence can be submitted in opposition. NGOs, government bodies, and industry associations can file pre-grant opposition to prevent biopiracy patents. Process: File Form 7A with grounds and evidence → Controller constitutes Opposition Board → Hearing → Decision.`,
    citation: "Patents Act, 1970, Section 25(1), 25(2); Patent Rules 2024, Rule 55-56; Form 7A",
    sourceUrl: "https://ipindia.gov.in",
    version: "As amended, 2024 Rules",
    effectiveDate: "2024-03-15",
    tags: "patent,opposition,pre_grant,post_grant,section_25,tkdl,biopiracy,form_7a,challenge",
    authorityLevel: "primary",
  },
  {
    title: "Section 3(i) - Methods of Agriculture and Horticulture",
    category: "statute",
    jurisdiction: "india",
    ipType: "patent",
    content: `Section 3(i) of the Patents Act excludes from patentability "any process for the medicinal, surgical, curative, prophylactic, diagnostic, therapeutic or other treatment of human beings or any process for a similar treatment of animals to render them free of disease or to increase their economic value or that of their products." SIGNIFICANCE FOR AYURVEDA: (1) Ayurvedic treatment METHODS (e.g., Panchakarma procedures, specific massage techniques, diagnostic methods) are NOT patentable; (2) However, PRODUCTS used in treatment CAN be patentable if they meet other criteria; (3) Medical devices/instruments used in Ayurvedic treatment may be patentable; (4) This distinction is crucial: you cannot patent the Panchakarma procedure itself, but you can potentially patent a novel oil formulation used in Panchakarma.`,
    citation: "Patents Act, 1970, Section 3(i); Patent Office Manual of Patent Practice and Procedure",
    sourceUrl: "https://ipindia.gov.in",
    version: "As amended",
    effectiveDate: "2005-01-01",
    tags: "patent,section_3i,treatment_method,panchakarma,diagnostic,therapeutic,non_patentable,medical",
    authorityLevel: "primary",
  },
];
